// ═══════════════════════════════════════════════════
// BitWet — data.js
// Crag database, regions, and defaults
// Edit this file to add/modify crags and regions
// ═══════════════════════════════════════════════════

const DEFAULT_CRAGS = [
  { id: 'sobrio', name: 'Sobrio', region: 'Ticino', lat: 46.480, lon: 8.920, alt: 950, orientation: ['S','SE','SW'], rock: 'Gneiss', notes: 'Small mountain roads to parking. 10 min hike down to crag. Great 6b–7a range.' },
  { id: 'sunneplaettli', name: 'Sunneplättli', region: 'Schwyz (Gersau)', lat: 46.994, lon: 8.524, alt: 650, orientation: ['S','SW'], rock: 'Limestone', notes: 'Above Vierwaldstättersee. Can be crowded on weekends. Climbable in winter on sunny days.' },
  { id: 'handegg', name: 'Handegg', region: 'Berner Oberland (Grimsel)', lat: 46.717, lon: 8.305, alt: 1400, orientation: ['S','SW'], rock: 'Granite', notes: 'Grimselpass area. Multi-pitch and single pitch on superb granite. Summer crag (snow until May).' },
  { id: 'schoellenen', name: 'Schöllenen', region: 'Uri (Göschenen)', lat: 46.665, lon: 8.588, alt: 1000, orientation: ['S','SE'], rock: 'Granite', notes: 'Dramatic gorge setting near Andermatt. Granite walls with routes 6a–7c. Summer best.' },
  { id: 'lehn', name: 'Lehn', region: 'Berner Oberland (Interlaken)', lat: 46.688, lon: 7.848, alt: 800, orientation: ['S','SW'], rock: 'Limestone', notes: 'One of Switzerland\'s most varied crags. Good 6b–7b selection. Can get busy.' },
  { id: 'salvan', name: 'Salvan', region: 'Wallis (Bas-Valais)', lat: 46.120, lon: 7.020, alt: 900, orientation: ['S','SE','SW'], rock: 'Gneiss', notes: '120+ routes 5a–9a. Perfect gneiss, aesthetic lines. Nature campsite at Van d\'en Haut.' },
  { id: 'cadarese', name: 'Cadarese', region: 'Ossola Valley (IT border)', lat: 46.280, lon: 8.300, alt: 700, orientation: ['S','SW'], rock: 'Granite', notes: 'Just across the Italian border. World class granite crack climbing. Also sport routes 6a–8a. Quiet, raw setting.' },
  { id: 'felliberg', name: 'Felliberg', region: 'Uri (Amsteg)', lat: 46.736, lon: 8.641, alt: 1200, orientation: ['S','SE'], rock: 'Granite', notes: 'Good summer crag for hot days. 40 min approach. Routes 5b–8a. Quiet and alpine.' },
  { id: 'dri-horlini', name: 'Dri Horlini', region: 'Wallis (Saastal)', lat: 46.105, lon: 7.945, alt: 2100, orientation: ['S','SW'], rock: 'Gneiss', notes: 'High alpine crag near Almagellerhütte. Bolted sport routes. 2h approach. July–Sept.' },
  { id: 'gotthard-tremola', name: 'Gotthard Tremola', region: 'Ticino (Airolo)', lat: 46.555, lon: 8.565, alt: 1800, orientation: ['S','SE'], rock: 'Granite', notes: 'Near old Tremola road. Coarse granite, good friction. Summer crag at altitude.' },
  { id: 'vals-platz', name: 'Vals', region: 'Graubünden', lat: 46.617, lon: 9.180, alt: 1250, orientation: ['S','SW'], rock: 'Gneiss', notes: 'Beautiful Vals valley. Gneiss sport climbing. Quiet area, good camping. Routes 5c–7b.' },
  { id: 'chironico-sport', name: 'Chironico (Sport)', region: 'Ticino', lat: 46.445, lon: 8.855, alt: 750, orientation: ['S','SE'], rock: 'Gneiss', notes: 'Not just bouldering — sport sectors 6a–7c on superb gneiss. South-facing, sheltered. Oct–Apr best.' },
];

const REGIONS = [
  { id: 'ticino', name: 'Ticino', sub: 'Cresciano / Bellinzona', lat: 46.23, lon: 8.96, alt: 500 },
  { id: 'wallis', name: 'Wallis / Valais', sub: 'Saas / Visp area', lat: 46.30, lon: 7.88, alt: 800 },
  { id: 'berner-oberland', name: 'Berner Oberland', sub: 'Interlaken area', lat: 46.69, lon: 7.86, alt: 700 },
  { id: 'zentralschweiz', name: 'Zentralschweiz', sub: 'Gersau / Rigi area', lat: 46.99, lon: 8.52, alt: 600 },
  { id: 'jura', name: 'Jura', sub: 'Basel / Delémont', lat: 47.37, lon: 7.35, alt: 500 },
  { id: 'ostschweiz', name: 'Ostschweiz / Graubünden', sub: 'Chur area', lat: 46.85, lon: 9.53, alt: 600 },
  { id: 'gotthard', name: 'Gotthard / Uri', sub: 'Sustenpass area', lat: 46.73, lon: 8.45, alt: 1200 },
  { id: 'voralpen', name: 'Voralpen', sub: 'Engelberg area', lat: 46.82, lon: 8.40, alt: 900 },
];

// ~10 crags per region for the Explore tab
const REGION_CRAGS = {
  'ticino': [
    { name: 'Ponte Brolla', lat: 46.193, lon: 8.745, alt: 300, rock: 'Gneiss', orientation: ['S','SW'], grades: '4a–7c' },
    { name: 'Arcegno', lat: 46.170, lon: 8.730, alt: 400, rock: 'Gneiss', orientation: ['S','SE'], grades: '5a–7b' },
    { name: 'Balladrum', lat: 46.165, lon: 8.725, alt: 350, rock: 'Gneiss', orientation: ['S'], grades: '4c–7a' },
    { name: 'Cresciano (Sport)', lat: 46.228, lon: 8.995, alt: 400, rock: 'Gneiss', orientation: ['S','SW'], grades: '5b–8a' },
    { name: 'Claro', lat: 46.258, lon: 9.043, alt: 500, rock: 'Gneiss', orientation: ['S','SE'], grades: '5c–8c' },
    { name: 'Chironico (Sport)', lat: 46.445, lon: 8.855, alt: 750, rock: 'Gneiss', orientation: ['S','SE'], grades: '6a–7c' },
    { name: 'Sobrio', lat: 46.480, lon: 8.920, alt: 950, rock: 'Gneiss', orientation: ['S','SE','SW'], grades: '5c–7b' },
    { name: 'El Cat (Brontallo)', lat: 46.345, lon: 8.605, alt: 700, rock: 'Gneiss', orientation: ['S','SW'], grades: '5c–7b' },
    { name: 'Eus (Verzasca)', lat: 46.280, lon: 8.870, alt: 500, rock: 'Gneiss', orientation: ['S'], grades: '6a–8a' },
    { name: 'Prato Sornico', lat: 46.395, lon: 8.620, alt: 800, rock: 'Gneiss', orientation: ['SW','W'], grades: '6a–7c' },
  ],
  'wallis': [
    { name: 'Salvan', lat: 46.120, lon: 7.020, alt: 900, rock: 'Gneiss', orientation: ['S','SE','SW'], grades: '5a–9a' },
    { name: 'Dri Horlini', lat: 46.105, lon: 7.945, alt: 2100, rock: 'Gneiss', orientation: ['S','SW'], grades: '5c–7a' },
    { name: 'Saillon', lat: 46.168, lon: 7.190, alt: 500, rock: 'Limestone', orientation: ['S'], grades: '5b–7c' },
    { name: 'Dorénaz', lat: 46.148, lon: 7.050, alt: 600, rock: 'Gneiss', orientation: ['S','SE'], grades: '5c–7b' },
    { name: 'Vercorin', lat: 46.268, lon: 7.530, alt: 1200, rock: 'Gneiss', orientation: ['S','SW'], grades: '5b–7a' },
    { name: 'Nax', lat: 46.225, lon: 7.428, alt: 1000, rock: 'Limestone', orientation: ['S'], grades: '5c–7b' },
    { name: 'Raron', lat: 46.315, lon: 7.795, alt: 700, rock: 'Limestone', orientation: ['S','SW'], grades: '6a–8a' },
    { name: 'Bitsch', lat: 46.355, lon: 7.990, alt: 800, rock: 'Gneiss', orientation: ['S'], grades: '5c–7a' },
    { name: 'Fieschertal (Burg)', lat: 46.432, lon: 8.133, alt: 1700, rock: 'Granite', orientation: ['S','SE'], grades: '5a–7a' },
    { name: 'Stalden', lat: 46.235, lon: 7.870, alt: 750, rock: 'Gneiss', orientation: ['S','SW'], grades: '5c–7b' },
  ],
  'berner-oberland': [
    { name: 'Lehn', lat: 46.688, lon: 7.848, alt: 800, rock: 'Limestone', orientation: ['S','SW'], grades: '5b–8a' },
    { name: 'Handegg', lat: 46.717, lon: 8.305, alt: 1400, rock: 'Granite', orientation: ['S','SW'], grades: '5a–7a' },
    { name: 'Gimmelwald', lat: 46.548, lon: 7.882, alt: 1400, rock: 'Limestone', orientation: ['S'], grades: '5c–9a' },
    { name: 'Elsigen', lat: 46.505, lon: 7.640, alt: 1200, rock: 'Limestone', orientation: ['S','SW'], grades: '5a–8c' },
    { name: 'Kandersteg', lat: 46.497, lon: 7.670, alt: 1200, rock: 'Limestone', orientation: ['S','SE'], grades: '5b–7b' },
    { name: 'Innertkirchen', lat: 46.710, lon: 8.230, alt: 700, rock: 'Granite', orientation: ['S','SW'], grades: '5c–7a' },
    { name: 'Bächlital', lat: 46.680, lon: 8.290, alt: 1800, rock: 'Granite', orientation: ['S','SE'], grades: '5b–6c' },
    { name: 'Guttannen', lat: 46.680, lon: 8.290, alt: 1100, rock: 'Granite', orientation: ['S'], grades: '5c–7b' },
    { name: 'Meiringen (Hasliberg)', lat: 46.735, lon: 8.185, alt: 800, rock: 'Limestone', orientation: ['S','SW'], grades: '5b–7c' },
    { name: 'Rosenlaui', lat: 46.730, lon: 8.165, alt: 1400, rock: 'Limestone', orientation: ['SE','S'], grades: '6a–8b' },
  ],
  'zentralschweiz': [
    { name: 'Sunneplättli (Gersau)', lat: 46.994, lon: 8.524, alt: 650, rock: 'Limestone', orientation: ['S','SW'], grades: '4a–7c' },
    { name: 'Föhnenberg (Gersau)', lat: 46.990, lon: 8.510, alt: 750, rock: 'Limestone', orientation: ['S'], grades: '5c–7b' },
    { name: 'Sattelflüe (Gersau)', lat: 46.985, lon: 8.530, alt: 700, rock: 'Limestone', orientation: ['S','SE'], grades: '5b–7a' },
    { name: 'Chileflue (Gersau)', lat: 46.997, lon: 8.520, alt: 600, rock: 'Limestone', orientation: ['S','SW'], grades: '4c–6c' },
    { name: 'Morschach', lat: 46.975, lon: 8.650, alt: 700, rock: 'Limestone', orientation: ['S'], grades: '5a–7a' },
    { name: 'Brüggler', lat: 46.950, lon: 8.898, alt: 1200, rock: 'Limestone', orientation: ['S','SW'], grades: '5b–8a' },
    { name: 'Voralpsee', lat: 47.105, lon: 9.215, alt: 1100, rock: 'Limestone', orientation: ['S','SW'], grades: '6a–7c' },
    { name: 'Sisikon', lat: 46.940, lon: 8.640, alt: 500, rock: 'Limestone', orientation: ['S'], grades: '5c–7b' },
    { name: 'Flüelen', lat: 46.900, lon: 8.630, alt: 500, rock: 'Limestone', orientation: ['S','SE'], grades: '5b–7a' },
    { name: 'Isenthal', lat: 46.910, lon: 8.570, alt: 800, rock: 'Limestone', orientation: ['S','SW'], grades: '5c–7b' },
  ],
  'jura': [
    { name: 'Pelzmühle', lat: 47.398, lon: 7.375, alt: 500, rock: 'Limestone', orientation: ['S','SE'], grades: '5a–7c' },
    { name: 'Löwenburg', lat: 47.380, lon: 7.355, alt: 550, rock: 'Limestone', orientation: ['S'], grades: '5b–7b' },
    { name: 'Hasenmatt', lat: 47.230, lon: 7.440, alt: 900, rock: 'Limestone', orientation: ['S','SW'], grades: '5c–7a' },
    { name: 'Bärschwil', lat: 47.375, lon: 7.490, alt: 500, rock: 'Limestone', orientation: ['S'], grades: '5b–7a' },
    { name: 'Metzerlen', lat: 47.445, lon: 7.455, alt: 450, rock: 'Limestone', orientation: ['S','SE'], grades: '5a–7b' },
    { name: 'Zullwil', lat: 47.385, lon: 7.515, alt: 500, rock: 'Limestone', orientation: ['S','SW'], grades: '5b–6c' },
    { name: 'Balsthal', lat: 47.316, lon: 7.695, alt: 550, rock: 'Limestone', orientation: ['S'], grades: '5c–7c' },
    { name: 'Oensingen', lat: 47.285, lon: 7.720, alt: 500, rock: 'Limestone', orientation: ['S','SW'], grades: '5b–7a' },
    { name: 'Raimeux', lat: 47.348, lon: 7.370, alt: 700, rock: 'Limestone', orientation: ['S','SE'], grades: '5a–7b' },
    { name: 'Moutier', lat: 47.278, lon: 7.370, alt: 600, rock: 'Limestone', orientation: ['S'], grades: '5c–7c' },
  ],
  'ostschweiz': [
    { name: 'Galerie (Amden)', lat: 47.141, lon: 9.124, alt: 900, rock: 'Limestone', orientation: ['S','SW'], grades: '4b–8c' },
    { name: 'Chinesische Mauer', lat: 47.330, lon: 9.435, alt: 500, rock: 'Limestone', orientation: ['S'], grades: '6b–8b' },
    { name: 'Haldenstein', lat: 46.885, lon: 9.520, alt: 600, rock: 'Limestone', orientation: ['S','SW'], grades: '5b–7c' },
    { name: 'Vals', lat: 46.617, lon: 9.180, alt: 1250, rock: 'Gneiss', orientation: ['S','SW'], grades: '5c–7b' },
    { name: 'Calanda (Chur)', lat: 46.870, lon: 9.510, alt: 700, rock: 'Limestone', orientation: ['S'], grades: '5c–7b' },
    { name: 'Pfäfers (Bad Ragaz)', lat: 46.990, lon: 9.500, alt: 650, rock: 'Limestone', orientation: ['S','SE'], grades: '5b–7a' },
    { name: 'Murgtal', lat: 47.080, lon: 9.200, alt: 900, rock: 'Granite', orientation: ['S','SW'], grades: '5c–7b' },
    { name: 'Engi', lat: 46.975, lon: 9.155, alt: 800, rock: 'Limestone', orientation: ['S'], grades: '5b–7a' },
    { name: 'Klöntal', lat: 47.040, lon: 8.960, alt: 900, rock: 'Limestone', orientation: ['S','SW'], grades: '5c–7c' },
    { name: 'Flims', lat: 46.835, lon: 9.280, alt: 1100, rock: 'Limestone', orientation: ['S','SE'], grades: '5b–7b' },
  ],
  'gotthard': [
    { name: 'Schöllenen', lat: 46.665, lon: 8.588, alt: 1000, rock: 'Granite', orientation: ['S','SE'], grades: '5b–7c' },
    { name: 'Felliberg', lat: 46.736, lon: 8.641, alt: 1200, rock: 'Granite', orientation: ['S','SE'], grades: '5b–8a' },
    { name: 'Gotthard Tremola', lat: 46.555, lon: 8.565, alt: 1800, rock: 'Granite', orientation: ['S','SE'], grades: '5c–7a' },
    { name: 'Sustenpass', lat: 46.732, lon: 8.445, alt: 2000, rock: 'Granite', orientation: ['S','SW'], grades: '5b–7b' },
    { name: 'Furkapass', lat: 46.575, lon: 8.415, alt: 2100, rock: 'Granite', orientation: ['S','SW'], grades: '5c–7a' },
    { name: 'Göschenen', lat: 46.668, lon: 8.590, alt: 1100, rock: 'Granite', orientation: ['S','SE','SW'], grades: '5b–7c' },
    { name: 'Wassen', lat: 46.710, lon: 8.598, alt: 900, rock: 'Granite', orientation: ['S'], grades: '5c–7a' },
    { name: 'Realp', lat: 46.598, lon: 8.505, alt: 1550, rock: 'Granite', orientation: ['S','SW'], grades: '5b–6c' },
    { name: 'Nufenenpass', lat: 46.478, lon: 8.385, alt: 2100, rock: 'Granite', orientation: ['S'], grades: '5c–7a' },
    { name: 'Piansecco', lat: 46.538, lon: 8.490, alt: 1700, rock: 'Granite', orientation: ['S','SE'], grades: '5b–7b' },
  ],
  'voralpen': [
    { name: 'Engelberg (Brunnistöckli)', lat: 46.820, lon: 8.410, alt: 1100, rock: 'Limestone', orientation: ['S','SW'], grades: '5b–7b' },
    { name: 'Melchsee-Frutt', lat: 46.775, lon: 8.270, alt: 1900, rock: 'Limestone', orientation: ['S'], grades: '5c–7a' },
    { name: 'Planplatten', lat: 46.765, lon: 8.245, alt: 2100, rock: 'Limestone', orientation: ['S','SE'], grades: '5b–6c' },
    { name: 'Erstfeld', lat: 46.820, lon: 8.650, alt: 600, rock: 'Granite', orientation: ['S'], grades: '5c–7b' },
    { name: 'Attinghausen', lat: 46.870, lon: 8.615, alt: 600, rock: 'Limestone', orientation: ['S','SW'], grades: '5b–7a' },
    { name: 'Brunni (Engelberg)', lat: 46.810, lon: 8.395, alt: 1600, rock: 'Limestone', orientation: ['S','SE'], grades: '5a–7a' },
    { name: 'Grafenort', lat: 46.840, lon: 8.380, alt: 600, rock: 'Limestone', orientation: ['S'], grades: '5c–7b' },
    { name: 'Stans', lat: 46.960, lon: 8.365, alt: 500, rock: 'Limestone', orientation: ['S','SW'], grades: '5b–6c' },
    { name: 'Wolfenschiessen', lat: 46.910, lon: 8.395, alt: 600, rock: 'Limestone', orientation: ['S'], grades: '5c–7a' },
    { name: 'Sarnen (Ewil)', lat: 46.895, lon: 8.235, alt: 700, rock: 'Limestone', orientation: ['S','SE'], grades: '5b–7b' },
  ],
};
